/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */
function CameraClient(url) {
    this.url = url;
    var id = 1;
    
    function doJsonRpcRequest(method, params, methodCall, callback_success, callback_error) {
        var request = {};
        if (methodCall)
            request.id = id++;
        request.jsonrpc = "2.0";
        request.method = method;
        if (params !== null) {
            request.params = params;
        }
        JSON.stringify(request);
        
        $.ajax({
            type: "POST",
            url: url,
            data: JSON.stringify(request),
            success: function (response) {
                if (methodCall) {
                    if (response.hasOwnProperty("result") && response.hasOwnProperty("id")) {
                        callback_success(response.id, response.result);
                    } else if (response.hasOwnProperty("error")) {
                        if (callback_error != null)
                            callback_error(response.error.code,response.error.message);
                    } else {
                        if (callback_error != null)
                            callback_error(-32001, "Invalid Server response: " + response);
                    }
                }
            },
            error: function () {
                if (methodCall)
                    callback_error(-32002, "AJAX Error");
            },
            dataType: "json"
        });
        return id-1;
    }
    this.doRPC = function(method, params, methodCall, callback_success, callback_error) {
        return doJsonRpcRequest(method, params, methodCall, callback_success, callback_error);
    }
}

CameraClient.prototype.system_reboot = function(password, callbackSuccess, callbackError) {
    var params = {password : password};
    return this.doRPC("system_reboot", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.system_shutdown = function(password, callbackSuccess, callbackError) {
    var params = {password : password};
    return this.doRPC("system_shutdown", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.system_mode = function(mode, callbackSuccess, callbackError) {
    var params = {mode : mode};
    return this.doRPC("system_mode", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.system_state = function(callbackSuccess, callbackError) {
    var params = null;
    return this.doRPC("system_state", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.file_tree = function(filepath, callbackSuccess, callbackError) {
    var params = {filepath : filepath};
    return this.doRPC("file_tree", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.calib_control = function(command, callbackSuccess, callbackError) {
    var params = {command : command};
    return this.doRPC("calib_control", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.calib_mode = function(mode, callbackSuccess, callbackError) {
    var params = {mode : mode};
    return this.doRPC("calib_mode", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.calib_option = function(option, callbackSuccess, callbackError) {
    var params = {option : option};
    return this.doRPC("calib_option", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.calib_state = function(callbackSuccess, callbackError) {
    var params = null;
    return this.doRPC("calib_state", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.live_control = function(command, callbackSuccess, callbackError) {
    var params = {command : command};
    return this.doRPC("live_control", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.live_state = function(callbackSuccess, callbackError) {
    var params = null;
    return this.doRPC("live_state", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.live_set_field = function(corners, callbackSuccess, callbackError) {
    var params = {corners : corners};
    return this.doRPC("live_set_field", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.live_get_field = function(callbackSuccess, callbackError) {
    var params = null;
    return this.doRPC("live_get_field", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.upload_control = function(a_command, b_filepath, callbackSuccess, callbackError) {
    var params = {a_command : a_command, b_filepath : b_filepath};
    return this.doRPC("upload_control", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.upload_state = function(callbackSuccess, callbackError) {
    var params = null;
    return this.doRPC("upload_state", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.replay_control = function(a_command, b_filepath, callbackSuccess, callbackError) {
    var params = {a_command : a_command, b_filepath : b_filepath};
    return this.doRPC("replay_control", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.replay_state = function(callbackSuccess, callbackError) {
    var params = null;
    return this.doRPC("replay_state", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.stitch_control = function(a_command, b_filepath, callbackSuccess, callbackError) {
    var params = {a_command : a_command, b_filepath : b_filepath};
    return this.doRPC("stitch_control", params, true, callbackSuccess, callbackError);
};
CameraClient.prototype.stitch_state = function(callbackSuccess, callbackError) {
    var params = null;
    return this.doRPC("stitch_state", params, true, callbackSuccess, callbackError);
};
